name: ci

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ahmedovelshan/my_flask_app:latest

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1


      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash  

      - name: Run Helm chart
        run: |
          helm install my-flask-app ./my_flask_app

      - name: Run application tests
        run: |
          sleep 60
          kubectl port-forward service/my-flask-app-flask-app 5000:5000
          kubectl get services
          curl http://localhost:30500/health
  
      # Optional: Clean up kind cluster
      - name: Delete kind cluster
        run: kind delete cluster

