name: Create Cluster

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kind
        uses: helm/kind-action@v1
